### PR TITLE
NetCore Support

### PR DESCRIPTION
**Pull request by dev-bre**
In order to support NetCore in a multi target configuration, I had to create a new NetCore project first and make that project to support net450. That's why you will see files deleted and recreated.

There were also a multitude of files not actually used.

### CODE REVIEW

**Comment by dev-bre** [comment]
I can't really do much with these conflicts:

Syn.Speech.Test/bin/Debug/Syn.Speech.Test.exe
Syn.Speech.Test/bin/Debug/Syn.Speech.Test.pdb
Syn.Speech.Test/bin/Debug/Syn.Speech.dll
Syn.Speech.Test/bin/Debug/Syn.Speech.pdb

These files should not be part of the repo at all.

**Comment by SynOfficial** [comment]
Thanks for the PR, we'll are taking a look at it. We'll try to resolve the conflicts and then get the commit merged.

**Review by SynOfficial — APPROVED** [review]

**Comment by cartheur** [comment]
It would be wise to sort the conflicts on this branch.

**Comment by cartheur** [comment]
I can surmise by the closing of the PR that there is no NetCore port?

**Comment by SynOfficial** [comment]
We too regret not being able to fix merge conflicts on time.

Nonetheless changes were made to target .NET 6.0 (LTS)

https://www.nuget.org/packages/Syn.Speech/

**Pull request closed without merging**
